### PR TITLE
Added more options to Session constructor

### PR DESCRIPTION
**Pull request by ddolcimascolo**

### CODE REVIEW

**Comment by ddolcimascolo** [comment]
Hey @calmh,

Any news on this? 
If you're out of time or don't maintain the repo anymore I'll be glad to help :)

Regards, 
David

**Comment by ddolcimascolo** [comment]
Hi @calmh,

Up again! 

Thx, 
David

**Comment by ddolcimascolo** [comment]
Hello @calmh,

Did you get any chance to review this? 

Thx, 
David

**Comment by calmh** [comment]
Yeah, sorry. It's effectively unmaintained, but sometimes things happen.

**Comment by ddolcimascolo** [comment]
Excellent, thanks for the merge and the invite.

David

**Comment by ddolcimascolo** [comment]
@calmh 

Any chance you can give me access to the NPM package too, so that I can release and push new versions?

Thx !

David

**Comment by calmh** [comment]
I've been holding off on delegating that, but I've pushed a new release now!

**Comment by ddolcimascolo** [comment]
Excellent, thx!

**Pull request merged**
